### ISSUE TITLE
cannot install Scrum-it

### ISSUE THREAD

**Issue by emiliaipate** [ti-dev/Scrum-it#1]
Hi there,

I have followed the installation instructions, but something is not ok.
tomcat is running ok and I can access this page: http://localhost:8080/scrumit/ But i get a page back that has only external links and no button to actually see a board and play with stories/tasks.

I have installed Mysql with the default settings and I  have updated hibernate.cgf.xml (within the deployed scrumit folder) with:
<property name="connection.url">jdbc:mysql://localhost:3306/scrumit</property>
<property name="connection.username">root</property>
<property name="connection.password">ajutor</property>

I have created the scrumit database, but the tables are never created no matter how many times I stop and restart tomcat and go to http://localhost:8080/scrumit/.

Any ideas what I might be doing wrong?

Emilia

**Comment by ti-dev** [comment]
Can you try to access it with http://localhost:8080/scrumit/project/

**Comment by akashneural** [comment]
i am also facing the same issue... 
need brief instructions for the installation.

**Comment by ti-dev** [comment]
Please tell me how can I help you?

Did you already read the short installation guide?
Take a look here: http://sourceforge.net/projects/scrum-it/files/Scrum-it-InstallationGuide.pdf/download

**Comment by enderim** [comment]
I installed Scrum-It as explained above pdf file, but main screen does not show the entrance of the real application, there is only a "Live Demo" choice, but all the information created get lost when I restart the tomcat server. Actually I can see the records created in the database, but after restart they are deleted.

So, why is the main screen used for advertisement, and there is only a live demo choice, and how can I make changes I've made persistent ?

**Comment by ti-dev** [comment]
Yes, it was the landing page, and so there is the label "Live Demo". You can delete this webpage or create your own.

After restart all records are deleted: It seems you did not change the "hbm2ddl" value to "none". Please take a look at the pdf file section "MySQL".

**Comment by enderim** [comment]
Thank you for the quick reply and for the project also. Yes, as you said, I've forgotten to change the "hbm2ddl" value, and it works fine with "none".
